Module1 task2
htmlacademy-yii/336921-task-force-2 pull request #2
Opened 2021-08-09 08:14 UTC by nerodemiurgo

Перечислены константы действий и статусов,
текущий статус и идентификаторы пользователей сохранены в свойствах,
описаны методы передачи действий и статусов,
описан метод вычисления действий для текущего статуса и роли,
описан метод вычисления следующего статуса по пришедшему действию,
убраны break перед return

2021-08-12 10:12 UTC, b1rdex requested changes

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +// Определять список из всех доступных действий
Комментарии к методам нужно оформлять как phpDoc
```suggestion
    /**
     * Определять список из всех доступных действий
     */
```

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +        $statuses = array_keys(self::STATUSES);
Тут вернётся 0,1,2....

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +        'new',                    //Статус новое
Нужно каждое значение вынести в отдельную константу: `const STATUS_NEW = 'new'`

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +       'to_cancel'       => ['cancel'],             //Отменить заказ
Каждое действие тоже вынести в константу

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +    public $role = "";                            //Роль пользователя, совершившего действий
Это всё стоит сделать private, значения по умолчанию не нужны, т.к. задаются в конструкторе

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +    public $action = "";                          //Пришедшее действие
Это не нужно

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +        if ($role = "customer") {
Роли тоже вынеси в константы

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +                return self::STATUSES['canceled'];
Таких ключей там нет

2021-08-12 10:12 UTC, b1rdex commented on Task.php
> +}
Нужно ещё написать файл test.php, в котором проверить результат вызова getActions и getNextStatus

2021-08-16 11:32 UTC, b1rdex requested changes

2021-08-16 11:32 UTC, b1rdex commented on test.php
> +    print($s." - ".$value."<br>");
В тестах должны быть какие-то проверки результатов, как вариант через assert()
Чтобы если появится ошибка в логике, тест завершался ошибкой

2021-08-16 11:32 UTC, b1rdex commented on test.php
> +    print($s." - ".$value."<br>");
Т.е. это не ручная проверка результатов print глазами

2021-08-16 11:32 UTC, b1rdex commented on Task.php
> +    public function __construct($current_status, $customer_id, $executor_id, $role)
По доп. критериям всем аргументам всех методов нужно проставлять типы

2021-08-16 11:32 UTC, b1rdex commented on Task.php
> +    public function getAllActions()
И возвращаемые типы всем методам тоже

2021-08-16 11:32 UTC, b1rdex commented on Task.php
> +        if ($this->role == self::ROLE_CUSTOMER) {
Стоит удалить $this->role и тут ты правильно добавила $role аргументом. Ведь по логике вещей, у задачи не может быть внутреннего состояния Роль. Но в момент выполнения метода getActions мы знаем для кого его вызываем и поэтому передаём $role.

2021-08-16 11:32 UTC, b1rdex commented on Task.php
> +            switch ($current_status) {
А с $current_status ситуация наоборот – это внутреннее состояние и мы уже храним его в $this->current_status. Поэтому аргумент $current_status нужно удалить и исправить условие

2021-08-16 11:32 UTC, b1rdex commented on test.php
> +require_once'Task.php';
По критериям код нужно форматировать в соответствии с PSR-2

2021-08-16 11:32 UTC, b1rdex commented on test.php
> +$action = "take_to_work";
Используй константы, для этого мы их и делали :)
```suggestion
$action = Task::ACTION_TO_TAKE_TO_WORK;
```

2022-01-26 08:58 UTC, sterlikoff requested changes
Ольга, в целом все хорошо, но есть пара моментов, на которые стоит обратить внимание:

1. Разработку следовало начать с написания интерфейса, от которого уже наследовать класс, в котором методы интерфейса реализуются. Наверное стоит повторить "Знакомство с ООП".

2. В методе getActions есть кейс, в котором функция может вообще ничего не вернуть (если role и не customer и не executor), а заявлено всегда string. Да, это как будто бы невозможно (с нашей точки зрения, а с точки зрения php - нет). А наша точка зрения может поменяться в ходе изменения ТЗ, например.

3. В тестах используешь нестрогие сравнения (==), старайся использовать строгие (===)

4. Старайся избегать автоприведения типов в assert так, чтобы первым аргументом всегда был bool:

assert(!empty($task->getAllStatuses()), 'Перечень статусов не возвращается');

2022-01-26 15:24 UTC, sterlikoff requested changes
Отлично, почти все :) 

Все еще хочу увидеть в классе наследование от интерфейса и еще обратил внимание, что `getActions` не участвует в тестах. 

Поправь пожалуйста это для зачета :)

2022-01-27 07:27 UTC, sterlikoff approved these changes
Ольга, теперь все отлично :) Зачет, идем дальше!

2022-01-27 07:27 UTC, merged